on:
  push:
    tags:
      - "v*"

jobs:
  build-and-upload:
    name: build and upload
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/actions/setup-gradle@v3

      - name: build
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          ./gradlew makePackages

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          path: build/generated/pkl/packages

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: build/generated/pkl/packages/*
